eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
server:
  port: 8085

# маршрутизация, используя идентификаторы служб
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true