spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
server:
  port: 8082

 #actuator
management:
  endpoints:
    enabled-by-default: true
    web:
#      base-path: /
      exposure:
        include:
          - '*'
  endpoint:
    health:
      enabled: true
      show-details: always

