spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
server:
  port: 8082

 #actuator
management:
  endpoints:
    web:
      base-path: /
  endpoint:
    health:
      show-details: always
